[package]
name = "rpgmxp-types"
version = "0.0.0"
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
ruby-marshal = { git = "https://github.com/nathaniel-daniel/ruby-marshal-rs", branch = "convert" }
serde = { version = "1.0.193", features = ["derive"] }
